Ansi007/Data-Structures-and-Algorithms

Algorithms/C++/LeetCode/1512. Number of Good Pairs/1512. Number of Good Pairs.cpp, Algorithms/C++/LeetCode/2236. Root Equals Sum of Children/2236. Root Equals Sum of Children.cpp, Algorithms/C++/LeetCode/4. Median of Two Sorted Arrays/4. Median of Two Sorted Arrays.cpp
Added Solutions of Three LeetCode Problems
- 4. Median of Two Sorted Arrays
- 1512. Number of Good Pairs
- 2236. Root Equals Sum of Children
=> Added Solutions of Three LeetCode Problems

Algorithms/C++/Shortest Path/source.cpp
- Added C++ code of "Find shortest path between two points in a matrix"
=> Added Shortest Path Solution

Data Structures/C++/Stack/MyStack - Copy.cpp, Data Structures/C++/Stack/MyStack - Copy.h
=> Stack.cpp Added

Algorithms/C++/FloydWarshal/FloydWarshalAlgorithm.cpp
Floyd Warshal Algorithm implementation is added
=> Added Floyd Warshal Algorithm

Algorithms/C++/Dequeue/Dequeue.cpp, Algorithms/C++/Dequeue/Dequeue_LinkedList.cpp
=> Dequeue.cpp

Data Structures/C++/Binary Search Tree/Bst
It is a complete code for Binary search tree.
=> Complete-BST

Data Structures/C++/Linked List/set of operations-LinkedList
#include <iostream>
using namespace std;
class Node {
public:
int data ;
Node *next;
Node *prev;
Node () {	}
Node(int data , Node *N = 0 , Node *P = 0) {
this-> data = data;
next = N;
prev = P;
}
};
class LinkedList{
Node *Head;
Node *Tail;
public:
LinkedList () {
Head = Tail = 0;
}
void print() {
Node *temp = Head;
while (temp) {
cout << "Data = " << temp->data << endl;
temp = temp->next;	
}
}
int addtotail(int e) {
if (Tail != 0) {
Tail = new Node(e , 0, Tail) ;
Tail->prev->next = Tail;	
}
else Head = Tail = new Node (e) ;
}
LinkedList unionoftwo(LinkedList &l) {
Node *temp = Head;
Node *t = l.Head;
LinkedList res;
while (temp != 0 and t!=0) {
if (temp->data < t->data) {
res.addtotail(temp->data) ;
temp = temp->next;
}
else if (temp->data > t->data) {
res.addtotail(t->data) ;
t = …
=> Set of operations-Linked List

Data Structures/C++/Linked List/Set of operations-LinkedList
#include <iostream>
using namespace std;
class Node {
public:
int data ;
Node *next;
Node *prev;
Node () {	}
Node(int data , Node *N = 0 , Node *P = 0) {
this-> data = data;
next = N;
prev = P;
}
};
class LinkedList{
Node *Head;
Node *Tail;
public:
LinkedList () {
Head = Tail = 0;
}
void print() {
Node *temp = Head;
while (temp) {
cout << "Data = " << temp->data << endl;
temp = temp->next;	
}
}
int addtotail(int e) {
if (Tail != 0) {
Tail = new Node(e , 0, Tail) ;
Tail->prev->next = Tail;	
}
else Head = Tail = new Node (e) ;
}
LinkedList unionoftwo(LinkedList &l) {
Node *temp = Head;
Node *t = l.Head;
LinkedList res;
while (temp != 0 and t!=0) {
if (temp->data < t->data) {
res.addtotail(temp->data) ;
temp = temp->next;
}
else if (temp->data > t->data) {
res.addtotail(t->data) ;
t = …
=> Set of Operations in Linked List

Algorithms/C++/SortingAlgorithms/selection_sort.cpp
This is a cpp program on selection sort using Cpp. It takes array size and array elements as input and prints the array elements in sorted format.
=> Selection sort using Cpp.

Algorithms/C++/SortingAlgorithms/mergesort4way.cpp
Please accept my solution for four way merged sort
=> Four way merge sort

Algorithms/C++/Binary Search/binarySearch.cpp, Algorithms/C++/Linear Search/linearSearch.cpp
please accept this for hacktoberfest 2022
=> added linear and binary search algorithms

Algorithms/C++/Shortest Path/Dijkstra Algorathim
implementation of  Dijkstra Algorathim
=> Create Dijkstra Algorathim

Algorithms/C++/Gnome Sort
=> Gnome Sort

Data Structures/C++/Graph/graph.cpp, Data Structures/C++/Graph/main.cpp, Data Structures/C++/Graph/queue.cpp, Data Structures/C++/Linked List/Set of operations-LinkedList
Graph data structure implemented with adjacency matrix technique with user defined Queue data structure(for BFS)
=> Added Graph Data Structure

Data Structures/C++/Stack/stackusingqueue.c
Please accept my solution.
Thank you.
=> Stack using Queue

Data Structures/C++/Array/array ADT.cpp
#include <iostream>
#include <cstdlib>
#include <ctime>
using namespace std;
class Array {
int *a , size , length ;
public:
Array (int size ) {
this->size = size ;
a = new int [size] ;
length = 0 ;
}
void addelement(int e) {
if (length < size) 
a[length++] = e;
else cout << "Not enough space to add " << e << endl ;
}
void insertelement(int index , int element) {
int i;
if (index > length) cout << cout << "Index out of bound.\n" ; 
else if (length < size ) {
for (i = length - 1 ; i > index -1; i--) 
a[i + 1] = a[i] ;	
a[index] = element ;
length ++ ;
}
else cout << "Not enough space to insert " << element << endl ;
}
int deleteelement(int index) {
int i , element;
if (index > length) return -1 ;
else {
element = a[index] ;
for (i = index ; i < length - 1 ; i++) 
a[i] = a[i+1] ;
length -- ; …
=> Create array ADT.cpp

Data Structures/C++/Stack/Stock span problem.cpp
Solving Stock Span Problem from Stack in CPP.
=> Stock span problem.cpp

Data Structures/C++/Binary Search Tree/Binary Tree Level Order Traversal
solution of Binary Tree Level Order Traversal in CPP.
=> Binary Tree Level Order Traversal.cpp

Data Structures/C++/Stack/Help Classmates.cpp
Solving Help Classmate in CPP.
=> Help Classmates.cpp

Data Structures/C++/Array/First and last occurrences of x.cpp
Solving 'First and last occurrences of x' in CPP.
=> First and last occurrences of x.cpp

Algorithms/C++/LeetCode/Symmetric_tree/Symmetric_tree.cpp
Solution of leetcode problem number 101: symmetric tree
=> Symmetric_tree.cpp

Algorithms/C++/LeetCode/3sum/Mayank_3sum_solution.cpp
Hello,
I have added solution of the leetcode problem 3sum in the repo Data-Structures and-Algorithms by following all the guidelines. Please accept this pull request.
Thank you.
=> Added 3sum Solution

Algorithms/C++/min_path_cost.cpp
=> Minimum path cost

Data Structures/C++/Graph/transpose_graph.cpp
=> Transpose of a graph

Algorithms/maxSum_subArray.c
Maximum Subarray Sum using all 3 methods.
Please accept my solution.
=> Maximum Subarray Sum

Algorithms/MatrixChainMultiplication.java
=> Matrix Chain Multiplication - DP

radix_sort.cpp
This code uses count sort function with some modifications.
=> I've added Radix-Sort Code.

back.cpp
check a given number is the power of 2.IF answer is true than return 1,If no than return 0
=> BIT Manipulation

Data Structures/C++/String Question/Revers_Words_In_String.cpp
You Can Paste All Your String Question Here
=> String Questions

DayOfYear.cpp
In this program we calculated the day of the year.
=> Day Of The Year

Algorithms/JobScheduling.java
=> Interval Scheduling

CHO-HAN game
=> Cho Han game

Python/stack.py
kindly consider this pull request i will add more python concepts later
=> a stack data structure is added

Fibonacci series.cpp
This program print fibonacci series
=> Fibonacci series

Student Linked List.cpp
I have created student data in linked list
=> I have created student singly linked list

Trapping Rain Water.cpp
Solution of Trapping Rain Water leetcode problem.
=> Trapping Rain Water.cpp

Singly Linked list complete.cpp, Stack in linked list.cpp
I have written complete code of Singly linked list where you can find all related functions included in Singly linked list.
=> Create Singly Linked list complete.cpp

Reverse Nodes in k-Group.cpp
solution of  Reverse Nodes in k-Group
=>  Reverse Nodes in k-Group.cpp
